### ISSUE TITLE
How to add a new file reference to a project?

### ISSUE THREAD

**Issue by m-revetria** [tomlokhorst/XcodeEdit#18]
Hi, I'm trying to edit a Xcode project by adding a new swift file to its targets but I couldn't figure out how to do it.

How can I add a new source file and add it to the project's targets?

Thanks!

**Comment by tomlokhorst** [comment]
Unfortunately, it's currently not yet possible to modify a project.

With the current version of Xcode.swift, it's only possible to read in a project file, and write it back out unmodified. 

There is a [pull request](https://github.com/tomlokhorst/Xcode.swift/pull/4) for adding support for modification, but that's out of date.

Xcode.swift can be used is in combination with some other tool that modifies the project.pbxproj file. Xcode.swift can read in an XML formatted file and write it back out as a OpenStep formatted file, thus reducing a git diff.
