### ISSUE TITLE
Crash If SourceTree contains Path with "SRCROOT"

### ISSUE THREAD

**Issue by dfleming** [tomlokhorst/XcodeEdit#25]
Our project file uses `SRCROOT` in some paths and when the SourceTree is built up, the SourceTreeFolder is unable to recognize the `SRCROOT` variable and returns nil instead of `.sourceRoot.` enum type.

The PBXReference object has a lazy var that performs a force unwrap which with a SourceTree thats nil, crashes.

**Comment by dfleming** [comment]
On closer inspection, this is likely an issue with our project file, closing

**Comment by tomlokhorst** [comment]
Just to note: The next version of XcodeEdit (currently in the release/2.0 branch), shouldn't crash anymore, even on broken project files. It has a lot more optionals and no force unwraps.

**Comment by dfleming** [comment]
Thanks for the update @tomlokhorst, great to hear!
