### ISSUE TITLE
 Internally inconsistent warning without any further detail about error

### ISSUE THREAD

**Issue by DanielAsher** [tomlokhorst/XcodeEdit#32]
Hi,

I use Rswift and after a project merge have been getting this warning:
```
warning: [R.swift] project.pbxproj is internally inconsistent.

Perhaps a merge conflict?
```
Obviously the detail of the inconsistency is missing, so very hard to fix. Would anyone know under what circumstances no info on error is generated?

From reading the code it looks like either `deadRefs` or `orphanObjs` must not be empty, but I can't see a code path that would generate an empty error detail.

thanks,

Daniel

**Comment by tomlokhorst** [comment]
That's weird, and shouldn't happen. It sounds like a bug in XcodeEdit.
I think there are either dead references or orphan objects, but for some reason they're not reported.

For debugging this issue, it would be really useful to have the project file. Would it be possible for you to send the project.pbxproj file? My email address is tom@lokhorst.eu

**Comment by DanielAsher** [comment]
Hi @tomlokhorst,

thanks for getting back so quick.

I'll try to email the project file later today.

Cheers,

Daniel

**Comment by tomlokhorst** [comment]
Closed due to inactivity
