### ISSUE TITLE
Command `pod lib lint` fails, if my library uses R.swift

### ISSUE THREAD

**Issue by till0xff** [tomlokhorst/XcodeEdit#36]
XcodeEdit generates invalid URLs for project files. PR #35 fixes it.

**Comment by tomlokhorst** [comment]
Thanks for the PR. 

Could you provide an example when an invalid URL is generated?

**Comment by till0xff** [comment]
Yes, https://github.com/till0xff/XcodeEditIssue36

**Comment by till0xff** [comment]
* `pod lib lint --no-clean`
* Open CocoaPods-Lint project in Xcode and build

Xcode displays the following warnings when building:
`warning: [R.swift] Filename and/or extension could not be parsed from URL: file:///var/folders/cy/qn3lmv5d2r3gbcxqs1m61c100000gp/T/CocoaPods-Lint-20181227-10265-nal79b-XcodeEditIssue36/Pods/Users/s.erokhin/Projs/XcodeEditIssue36/XcodeEditIssue36/Resources/Localizable.strings`

Valid path is `/Users/s.erokhin/Projs/XcodeEditIssue36/XcodeEditIssue36/Resources/Localizable.strings`

**Comment by tomlokhorst** [comment]
Thanks for the example project!

I've merged the PR with the fix, this will be in the next R.swift release.
