### ISSUE TITLE
Version 2.7.0 throws build warnings in Xcode 11 Beta 4

### ISSUE THREAD

**Issue by BrianBatchelder** [tomlokhorst/XcodeEdit#38]
> CompileSwift normal x86_64 /Users/brian.batchelder/source/ios-library-dev/Pods/XcodeEdit/Sources/XcodeEdit/PBXIdentifier.swift (in target 'XcodeEdit' from project 'Pods')
> warning: imported declaration 'UITableViewDiffableDataSourceCellProvider' could not be mapped to 'UITableViewDiffableDataSourceReference.CellProvider'
>  warning: imported declaration 'UICollectionViewDiffableDataSourceCellProvider' could not be mapped to 'UICollectionViewDiffableDataSourceReference.CellProvider'

I looked to update to 2.7.3, but it is not yet available via cocoapods.

**Comment by tomlokhorst** [comment]
XcodeEdit has no references to UIKit at all.
So I don’t think this warning is coming from XcodeEdit?

I’ve published 2.7.3 to CocoaPods.

**Comment by BrianBatchelder** [comment]
Huh. I'm unable to reproduce the warning today. Sorry about the hassle!

I did verify 2.7.3 installs from CocoaPods, builds without warning, and does everything I need it to.

Thanks!
