### ISSUE TITLE
Error parsing valid .xcodeproj

### ISSUE THREAD

**Issue by iteracticman** [tomlokhorst/XcodeEdit#39]
This appears to happen with projects cross-referencing other projects generated by CocoaPods when `generate_multiple_pod_projects` is enabled.

Seems like the problem is they have `projectReferences` with no `ProductGroup`s, which is perfectly fine for Xcode, but not XcodeEdit.

Example:
[LocalPod2.xcodeproj.zip](https://github.com/tomlokhorst/XcodeEdit/files/3689543/LocalPod2.xcodeproj.zip)

**Comment by iteracticman** [comment]
Seems like this would do fix it:

```patch
--- a/Sources/XcodeEdit/PBXObject.swift
+++ b/Sources/XcodeEdit/PBXObject.swift
@@ -64,11 +64,11 @@ public class PBXProject : PBXContainer {
   }
 
   public class ProjectReference {
-    public let ProductGroup: Reference<PBXGroup>
+    public let ProductGroup: Reference<PBXGroup>?
     public let ProjectRef: Reference<PBXFileReference>
 
     public required init(fields: Fields, allObjects: AllObjects) throws {
-      self.ProductGroup = allObjects.createReference(id: try fields.id("ProductGroup"))
+      self.ProductGroup = allObjects.createOptionalReference(id: try? fields.id("ProductGroup"))
       self.ProjectRef = allObjects.createReference(id: try fields.id("ProjectRef"))
     }
   }
```

**Comment by tomlokhorst** [comment]
Thanks for the example project, that's very helpful.

I've updated the library to correctly handle the missing ProductGroup (as well as a missing KnownAssetTags, on which it also failed).
