### ISSUE TITLE
Xcode 15 local package

### ISSUE THREAD

**Issue by aldk98** [tomlokhorst/XcodeEdit#43]
# Problem
Using R.swift 7.3.2 with an Xcode 15 project where a local package dependency with its own Assets ( including localizable files ) failed to compile.

Error log shows XCodeEdit not supporting object type `XCLocalSwiftPackageReference`:
`Unknown PBXObject subclass isa=XCLocalSwiftPackageReference`
There is no issue on using Xcode 14 with locally added package.

Is this an issue somebody is working on? I can try to tackle this issue.

**Comment by tomlokhorst** [comment]
Thanks for the report.

Nobody is currently looking into this. If you can create a PR with a fix, that would be great!

**Comment by aldk98** [comment]
Hi @tomlokhorst , ping me if there's anything to add.
